const User = require("../models/User");
const { sendEmail } = require("./auth");

// @desc Get all Users
// @route GET /api/v1/users
// @access Private
exports.getUsers = async (req, res, next) => {
  try {
    const user = await User.find();
    res
      .status(200)
      .json({
        success: true,
        msg: "Get All Users Successful",
        count: user.length,
        data: user,
      });
  } catch (err) {
    console.log(err.stack);
    res.status(400).json({ success: false, msg: "Can not get all Users" });
  }
};

// @desc Get one User
// @route GET /api/v1/user/:id
// @access Private
exports.getUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id);

    if (!user) {
      return res
        .status(404)
        .json({ success: false, message: "Cannot find User with provided ID" });
    }

    if (req.user != user && req.user.role !== "admin") {
      return res.status(400).json({
        success: false,
        message: "You are unauthorize to access this information",
      });
    }

    res
      .status(200)
      .json({ success: true, msg: "Get User Successful", data: user });
  } catch (err) {
    console.log(err.stack);
    res.status(400).json({ success: false, msg: "Can not get all Users" });
  }
};

// @desc Delete User
// @route DELETE /api/v1/user/:id
// @access Private
exports.deleteUser = async (req, res, next) => {
  try {
    const user = await User.findById(req.params.id);
    if (!user) {
      return res
        .status(404)
        .json({ success: false, message: "Cannot find User with provided ID" });
    }

    if (req.user.id != user.id && req.user.role !== "admin") {
      return res.status(400).json({
        success: false,
        message: "You are unauthorize to access this information",
      });
    }
    await sendEmail({
      email: user.email,
      subject: "[SABAAI Massage] Your Account Has Been Deleted",
      toUser: user.name,
      OTP: null,
      html: `<div style="max-width: 700px; margin: 40px auto; padding: 40px 30px; background: #ffffff; border-radius: 12px; box-shadow: 0 4px 20px rgba(16, 185, 129, 0.2); border: 1px solid #d1fae5;">
    <div style="text-align: center; margin-bottom: 30px;">
    <img src="https://i.postimg.cc/4xrSTJhz/temp-Image-BMx-Ka-M.avif" alt="SABAAI Logo" style="max-width: 200px; border-radius: 10px;" />
    </div>
    
    <h2 style="text-align: center; font-size: 24px; color: #065f46; margin-bottom: 20px;">Hi ${user.name},</h2>
    
    <p style="font-size: 16px; color: #10b981; font-weight: bold; margin-top: 30px;">Your SABAAI account has been deleted successfully.</p>
    
    <div style="font-size: 13px; color: #9ca3af; margin-top: 40px; text-align: left; border-top: 1px solid #e5e7eb; padding-top: 20px;">
    This message was generated by <a href="https://sabaai.vercel.app" style="color: #10b981; text-decoration: none;">https://sabaai.vercel.app/</a>.
    </div>
    </div>`,
    });
    await user.deleteOne();
    res
    .status(200)
      .json({ success: true, msg: "Delete successful", data: user });
    } catch (err) {
    console.log(err.stack);
    res.status(400).json({ success: false, msg: "Can not delete this User" });
  }
};
