import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    test.setTimeout(60000);
    await page.goto('https://sabaai.vercel.app/');
    await page.getByRole('link', { name: 'Sign In' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).click();
    await page.getByRole('textbox', { name: 'Email Address' }).fill('Michael.Myer@gmail.com');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('12345678');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.waitForTimeout(4000);
    await page.getByRole('link', { name: 'Shops' }).click();
    await page.locator('a > .w-full').first().click();
    await page.waitForTimeout(4000);
    await page.getByRole('button', { name: 'Edit Shop Services' }).click();
    await page.getByRole('textbox', { name: 'Service Name' }).click();
    await page.getByRole('textbox', { name: 'Service Name' }).fill('Test');
    await page.waitForTimeout(500);
    await page.getByRole('combobox', { name: 'Target Area' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('option', { name: 'Foot' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('combobox', { name: 'Massage Type' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('option', { name: 'Thai' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('textbox', { name: 'Detail' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('textbox', { name: 'Detail' }).fill('Test');
    await page.getByRole('spinbutton', { name: 'Price' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('spinbutton', { name: 'Price' }).fill('5');
    await page.getByRole('button', { name: 'Confirm' }).click();
    await page.waitForTimeout(2000);
    await page.locator('div.grid.grid-cols-1 > div.flex.flex-col').last().getByRole('button', { name: 'Delete' }).click();
    await page.waitForTimeout(500);
    await page.getByRole('button', { name: 'Confirm' }).nth(1).click();
    await page.waitForTimeout(2000);
    await expect(page.getByRole('main')).toContainText('Service deleted successfully!');
    const popup = page.locator('div.fixed.inset-0');
    await popup.getByRole('button', { name: 'Close' }).click();
    await page.waitForTimeout(1000);
});